# -*- coding: utf-8 -*-
{
    'name': 'DealFlow360',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'DealFlow360 Module Baseline',
    'description': """DealFlow360 - Odoo Hackathon 2026""",
    'author': 'DealFlow360 Team',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'sale', 'sale_stock', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/dealflow360_data.xml',
        'views/menus.xml',
        'views/discount_rule_views.xml',
        'views/customer_tier_views.xml',
        'views/approval_rule_views.xml',
        'views/approval_views.xml',
        'views/product_recommendation_views.xml',
        'views/fulfillment_plan_views.xml',
        'views/stock_warehouse_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/login_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dealflow360/static/src/js/dealflow_recommendations_widget.js',
            'dealflow360/static/src/xml/dealflow_recommendations_widget.xml',
            'dealflow360/static/src/js/command_center.js',
            'dealflow360/static/src/xml/command_center.xml',
            'dealflow360/static/src/js/sales_rep_workspace.js',
            'dealflow360/static/src/xml/sales_rep_workspace.xml',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
