from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError

class FulfillmentPlan(models.Model):
    _name = 'dealflow.fulfillment.plan'
    _description = 'DealFlow Fulfillment Plan'
    _order = 'generated_at desc'

    order_id = fields.Many2one('sale.order', string='Sale Order', required=True, ondelete='cascade')
    state = fields.Selection([
        ('draft', 'Draft'),
        ('validated', 'Validated'),
        ('applied', 'Applied')
    ], string='Status', default='draft', required=True, tracking=True)
    
    company_id = fields.Many2one('res.company', string='Company', required=True, default=lambda self: self.env.company)
    generated_at = fields.Datetime(string='Generated At', default=fields.Datetime.now, required=True)
    generated_by = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user, required=True)
    is_manual_override = fields.Boolean(string='Manual Override', default=False)

    allocation_ids = fields.One2many('dealflow.fulfillment.allocation', 'plan_id', string='Allocations')

    _sql_constraints = [
        ('unique_draft_validated_plan', 'unique(order_id, state) WHERE state IN (\'draft\', \'validated\')', 
         'Only one active (draft or validated) fulfillment plan is allowed per Sale Order.'),
    ]

    @api.constrains('company_id', 'order_id')
    def _check_company(self):
        for plan in self:
            if plan.order_id and plan.company_id != plan.order_id.company_id:
                raise ValidationError(_("The plan company must match the Sale Order company."))

    def action_validate_fulfillment_plan(self):
        for plan in self:
            if plan.state != 'draft':
                raise UserError(_("Only draft plans can be validated."))
            
            # Recompute and validate all allocations
            for alloc in plan.allocation_ids:
                if alloc.allocated_qty < 0:
                    raise UserError(_("Allocation quantity cannot be negative."))
                if alloc.warehouse_id.company_id != plan.company_id:
                    raise UserError(_("Warehouse must belong to the Sale Order company."))
            
            # Check totals per line
            line_allocs = {}
            for alloc in plan.allocation_ids:
                if alloc.line_id not in line_allocs:
                    line_allocs[alloc.line_id] = 0.0
                line_allocs[alloc.line_id] += alloc.allocated_qty
            
            for line, total in line_allocs.items():
                if total > line.product_uom_qty:
                    raise UserError(_("Total allocated quantity for product %s exceeds requested quantity.", line.product_id.display_name))
            
            plan.state = 'validated'


class FulfillmentAllocation(models.Model):
    _name = 'dealflow.fulfillment.allocation'
    _description = 'DealFlow Fulfillment Allocation'
    _order = 'line_id, warehouse_id'

    plan_id = fields.Many2one('dealflow.fulfillment.plan', string='Fulfillment Plan', required=True, ondelete='cascade')
    line_id = fields.Many2one('sale.order.line', string='Sale Order Line', required=True)
    warehouse_id = fields.Many2one('stock.warehouse', string='Warehouse', required=True)
    
    product_id = fields.Many2one(related='line_id.product_id', string='Product', store=True)
    requested_qty = fields.Float(related='line_id.product_uom_qty', string='Requested Qty', store=True)
    
    available_qty = fields.Float(string='Available Qty (Snapshot)', default=0.0)
    allocated_qty = fields.Float(string='Allocated Qty', default=0.0)
    
    backorder_qty = fields.Float(string='Backorder Qty', compute='_compute_backorder_qty', store=True)
    
    shipping_cost = fields.Float(string='Shipping Cost', default=0.0)
    is_manual_override = fields.Boolean(string='Manual Override', default=False)
    explanation = fields.Char(string='Explanation')

    @api.depends('allocated_qty', 'plan_id.allocation_ids', 'plan_id.allocation_ids.allocated_qty')
    def _compute_backorder_qty(self):
        for alloc in self:
            if not alloc.line_id or not alloc.plan_id:
                alloc.backorder_qty = 0.0
                continue
            
            # Sum all allocations for this exact line in this exact plan
            sibling_allocs = alloc.plan_id.allocation_ids.filtered(lambda a: a.line_id == alloc.line_id)
            total_allocated = sum(sibling_allocs.mapped('allocated_qty'))
            
            alloc.backorder_qty = max(0.0, alloc.requested_qty - total_allocated)

    @api.constrains('warehouse_id', 'plan_id')
    def _check_warehouse_company(self):
        for alloc in self:
            if alloc.warehouse_id.company_id != alloc.plan_id.company_id:
                raise ValidationError(_("Warehouse company must match the plan company."))

    def write(self, vals):
        if 'allocated_qty' in vals or 'warehouse_id' in vals:
            for alloc in self:
                if alloc.plan_id.state != 'draft':
                    raise UserError(_("Allocations can only be edited when the plan is in draft state."))
            vals['is_manual_override'] = True
            
        res = super(FulfillmentAllocation, self).write(vals)
        
        if 'allocated_qty' in vals or 'warehouse_id' in vals:
            for alloc in self:
                alloc.plan_id.write({'is_manual_override': True})
                
        return res
