[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$yVlrzZmzNqYUIqRUSqkVgg$mJRuuqmes4NCEElv4NBJ2xpg6mQJB58x9MWgApVdaf.e0aUA/0UZY4d7CnUzxGWIRiF8nMcCgIigIftaatWCYg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

